version: "3"
services:
    app:
        build: ./app
        depends_on:
          - db

    proxy:
        build: ./nginx
        ports:
          - "80:80"
        depends_on:
          - app       

    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"