version: "3.6"
services:
    app:
        build: ./asp
        depends_on:
          - db
        #restart: always
        container_name: kestrel  

    proxy:
        build: ./nginx
        ports:
          - "80:80"
        depends_on:
          - app
        #restart: always
        container_name: nginx         

    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        #restart: always
        ports:
          - "1433:1433"
        container_name: mssql    